version: '3'
services: 
  db:
    # build: ./db/
    image: postgres:13.3-alpine
    restart: always
    ports: 
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # healthcheck:
    #   test: "exit 0"

  app:
    build: ./
    restart: always
    ports: 
      - ${PORT}:${PORT}
    depends_on: 
      - 'db'
      # db:
      #   condition: service_healthy
    environment: 
        - PORT=4000




