version: '3.9'
services: 
  db:
    # build: ./db/
    image: postgres
    restart: always
    ports: 
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: "exit 0"
    volumes: 
      - my_docker_volume:/var/lib/mydb 

  app:
    build: ./
    restart: always
    ports: 
      - ${PORT}:${PORT}
    depends_on: 
      db:
        condition: service_healthy
    environment: 
        - PORT=4000
    volumes: 
      - B:\Р.А. Мухин Node_js\T.3\Task-3.-Debug-in-Node.js\db.js:/usr/app
          # - my_docker_volume:/usr/app 
        
    
volumes: 
  my_docker_volume:



